# anaconda

In [1]:
print("ganesh")

ganesh


In [7]:
i=1
print("enter the table value")
t=int(input())
print("choice to end value")
e=int(input())
for i in range(i,1+e):
    a=t*i
    print(i,"*",t,"=",a)


enter the table value
5
choice to end value
12
1 * 5 = 5
2 * 5 = 10
3 * 5 = 15
4 * 5 = 20
5 * 5 = 25
6 * 5 = 30
7 * 5 = 35
8 * 5 = 40
9 * 5 = 45
10 * 5 = 50
11 * 5 = 55
12 * 5 = 60


- datatype

In [7]:
type(10)

int

In [10]:
type(10.0)

float

In [35]:
type([1,2,3,4,5])

list

In [40]:
type([45.164])

list

In [5]:
type("gan")

str

In [9]:
"mathi"

'mathi'

In [10]:
a=10
b=20
c=56
print(a*b/c)

3.5714285714285716


In [11]:
print((a*b*c)+(b/a)*(a+b)*(b*58*45/85))

48047.05882352941


In [12]:
a="mathi"
b="guna"

In [13]:
print("myfirst name is {} and my last name is {}".format(a,b))

myfirst name is mathi and my last name is guna


## boolean

In [20]:
True and True

True

In [21]:
True and False

False

In [22]:
False and True

False

In [23]:
True and True

True

In [24]:
False and False

False

In [2]:
type(True)

bool

In [3]:
type(False)

bool

In [13]:
a="Mathi Guna"


In [14]:
a.istitle()

True

In [42]:
a="mathi"
b="gan"

In [45]:
a.isalnum() or b.isalnum()

True

## list

In [26]:
type([])

list

In [27]:
lst=["tamil","english","mat","sci",100,200,300,400,500]

In [28]:
print(lst)

['tamil', 'english', 'mat', 'sci', 100, 200, 300, 400, 500]


In [29]:
lst[2]

'mat'

In [30]:
lst[5]

200

In [31]:
type(lst)

list

In [32]:
len(lst)

9

In [35]:
lst[:]

['tamil', 'english', 'mat', 'sci', 100, 200, 300, 400, 500]

In [36]:
lst[2:]

['mat', 'sci', 100, 200, 300, 400, 500]

In [34]:
lst[1:6]

['english', 'mat', 'sci', 100, 200]

## insert

In [63]:
lst.append("soc")

In [64]:
lst

['tamil', 'english', 'mat', 'sci', 100, 200, 300, 400, 500, 'soc', 'soc']

In [69]:
lst.append("comsci")

In [70]:
lst

['tamil',
 'english',
 'mat',
 'sci',
 100,
 200,
 300,
 400,
 500,
 'soc',
 'soc',
 'comsci']

In [71]:
len(lst)

12

## extend

In [39]:
liste=[1,2,3,4,5,6]

In [40]:
liste

[1, 2, 3, 4, 5, 6]

In [41]:
liste.extend([7,8])

In [42]:
liste

[1, 2, 3, 4, 5, 6, 7, 8]

In [43]:
liste.extend([9,10,11,12])

In [44]:
liste

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [45]:
sum(liste)

78

## pop()method

In [46]:
liste.pop(8)

9

In [47]:
liste

[1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12]

In [50]:
liste.count(1)

1

## index

In [125]:
liste.index(5)

4

In [126]:
min(liste)

1

In [127]:
max(liste)

12

In [128]:
liste*2

[1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12]

In [131]:
l=int(input("how much time to multilied you like="))
l1=liste*l
print(l1)

how much time to multilied you like=5
[1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12]


In [141]:
i=int(input("enter the value="))
if(i%2==0):
    print("hi")
else:
    print("hello")


enter the value=10
hi


# sets

In [12]:
set_g={"gan","mathi","ram"}
print(set_g)
type(set_g)

setb={"gan","mathi","babu"}
print(setb)
type(setb)


{'gan', 'ram', 'mathi'}
{'gan', 'babu', 'mathi'}


set

In [13]:
set_g.add("arun")

In [14]:
print(set_g)

{'gan', 'ram', 'arun', 'mathi'}


In [15]:
set1={"avan","mar","dc","dis"}
set2={"avan","mar","dc","dis","mama"}

In [16]:
set2.difference(set1)

{'mama'}

In [17]:
set2.intersection(set1)

{'avan', 'dc', 'dis', 'mar'}

In [18]:
set2.intersection_update(set1)


In [19]:
set2

{'avan', 'dc', 'dis', 'mar'}

In [20]:
print(set1)
print(set2)


{'mar', 'avan', 'dis', 'dc'}
{'mar', 'avan', 'dis', 'dc'}


In [21]:
set2.difference(set1)

set()

In [22]:
set2

{'avan', 'dc', 'dis', 'mar'}

In [23]:
set2.difference_update(set1)

In [24]:
set2

set()

# dictionaries

In [54]:
dic={}

In [55]:
type(dic)

dict

In [60]:
dic={1,2,3,4,5,6}

In [61]:
type(dic)

set

In [74]:
my_dic={"car1":"audi","car2":"bmw","car3":"rr","car4":"benz"}

In [75]:
type(my_dic)

dict

In [77]:
my_dic["car1"]

'audi'

In [78]:
for i in my_dic:
    print(i)

car1
car2
car3
car4


In [82]:
for i in my_dic.values():
    print(i)

audi
bmw
rr
benz


In [83]:
for i in my_dic.items():
    print(i)

('car1', 'audi')
('car2', 'bmw')
('car3', 'rr')
('car4', 'benz')


In [84]:
## add a item

my_dic["car5"]="ferari"

In [85]:
my_dic

{'car1': 'audi', 'car2': 'bmw', 'car3': 'rr', 'car4': 'benz', 'car5': 'ferari'}

In [87]:
my_dic["car4"]="benzer"

In [88]:
my_dic

{'car1': 'audi',
 'car2': 'bmw',
 'car3': 'rr',
 'car4': 'benzer',
 'car5': 'ferari'}

In [3]:
arun={"a":1,"b":2,"c":3,"d":4,"e":6,"f":7,"g":10}

In [4]:
arun

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 6, 'f': 7, 'g': 10}

In [10]:
for i in arun.values():
    if i>=5:
        print(i)

6
7
10


In [1]:
mathi={"1":"arun","40":"mathi","50":"mama","20":"ganesh","10":"vengi","6":"sp","7":"hod","8":"mk"}

In [2]:
mathi

{'1': 'arun',
 '40': 'mathi',
 '50': 'mama',
 '20': 'ganesh',
 '10': 'vengi',
 '6': 'sp',
 '7': 'hod',
 '8': 'mk'}

In [3]:
ma=max(zip(mathi.keys(),mathi.values()))[1]
print(ma)

mk


In [8]:
ma=max(zip(mathi.keys(),mathi.values()))
print(ma)

('8', 'mk')


In [17]:
ma=max(zip(mathi.keys(),mathi.values()))
if ma<=5:
    print(ma)

TypeError: '<=' not supported between instances of 'tuple' and 'int'

In [36]:
j=[1,2,3,4,5,6,7,8,9,4,5,4,5,41,52,54,58,24,15,21,47,78,98]
print(max(j))

98


In [39]:
for i in mathi.keys():
    print(max(i))
        

1
2
3
4
5
6
7
8


In [19]:
for values,keys in mathi.items():
    if mathi.values,mathi.keys<=5:
        print(values,keys)
    

TypeError: '<=' not supported between instances of 'builtin_function_or_method' and 'int'

In [5]:
for i in mathi.keys():
    if i>=5:
        print(i)

5
6
7
8


## tuple

In [2]:
my_tuple=("gan","mathi","babu")

In [3]:
type(my_tuple)

tuple

In [4]:
print(my_tuple)

('gan', 'mathi', 'babu')


In [6]:
my_tuple=("hulk","than")

In [7]:
print(my_tuple)

('hulk', 'than')


In [11]:
my_tuple.count("hulk")

1

In [12]:
my_tuple.index("than")

1

## skils

In [3]:
print(1.0+2.0==3.0)

True


In [4]:
print(0.1+0.2==0.3)

False


In [13]:
type(())

tuple

In [14]:
type([])

list

In [15]:
type({})

dict

## numpy

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5,6]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.shape

(6,)

In [6]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[6,7,8,9]
array=np.array([list1,list2,list3])

In [7]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [8]:
print(array)

[[1 2 3 4]
 [5 6 7 8]
 [6 7 8 9]]


In [9]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [10]:
array.shape

(3, 4)

In [11]:
array.reshape(6,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [6, 7],
       [8, 9]])

In [12]:
array.shape

(3, 4)

## indexing

In [20]:
import numpy as np

In [26]:
li=int(input("enter the input"))

enter the input5


In [27]:

ar=np.array(li)

In [28]:
ar

array(5)

In [14]:
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [21]:
ar[5]

6

In [22]:
array[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [23]:
array[1:3,2:4]

array([[7, 8],
       [8, 9]])

In [24]:
ari=np.arange(0,10)

In [25]:
ari

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ari=np.arange(0,10,step=2)

In [27]:
ari

array([0, 2, 4, 6, 8])

In [28]:
ari[2]=100

In [46]:
ari

array([  0,   2, 100,   6,   8])

In [47]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
ra=np.arange(0,10)

In [49]:
ra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
ra[4:6]=100

In [51]:
ra

array([  0,   1,   2,   3, 100, 100,   6,   7,   8,   9])

In [52]:
ra[7:68]=500

In [53]:
ra

array([  0,   1,   2,   3, 100, 100,   6, 500, 500, 500])

In [54]:
import numpy as np

In [61]:
gane=np.arange(0,10)

In [62]:
print(gane)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
gane

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
gane_ex=np.random.randn(4,4)

In [70]:
gane_ex

array([[ 1.2950923 ,  1.40183181,  0.68356639, -0.03701949],
       [-2.18000574,  0.09570186, -0.17650016,  1.23201484],
       [ 0.65038981, -1.37383102, -2.2911605 , -0.35498153],
       [-0.21059459,  0.44071025, -0.57642806, -1.42463457]])

In [20]:
np.random.randint(0,100,8).reshape(2,4)

array([[67, 46, 35, 19],
       [ 8, 26, 46, 63]])

In [1]:
2+2

4

In [3]:
import numpy as np

In [6]:
li=input("enter the input")

enter the input[1,2,3,4,5,6,7,8,9]


In [7]:
lis=np.array(li)

In [8]:
lis

array('[1,2,3,4,5,6,7,8,9]', dtype='<U19')

In [10]:
a=(1,2,3,4,5,6,6,5,4,3)
print(a)

(1, 2, 3, 4, 5, 6, 6, 5, 4, 3)


In [12]:
b={1,2,2,3,3,4,5,6,5,4,3}
b

{1, 2, 3, 4, 5, 6}

In [13]:
b

{1, 2, 3, 4, 5, 6}

In [14]:
c={5,48,79,69,58,45,84,62,58,64,258}

In [15]:
c

{5, 45, 48, 58, 62, 64, 69, 79, 84, 258}

In [16]:
c

{5, 45, 48, 58, 62, 64, 69, 79, 84, 258}

In [19]:
ab=[1,2,3,4,5,6,7,8,9,4,5,6,1,2,3]
cd=tuple(ab)

In [20]:
print(cd)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 1, 2, 3)


In [21]:
ab

[1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 1, 2, 3]

In [22]:
ef=set(cd)

In [23]:
print(ef)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [29]:
a=(1,2,3,4,5,6)
a

(1, 2, 3, 4, 5, 6)

In [32]:
a.add(7)

AttributeError: 'tuple' object has no attribute 'add'

In [35]:
import calendar

year=2022
month=8

print(calendar.month(year,month,day))

                                August 2022
  Monday    Tuesday   Wednesday   Thursday    Friday    Saturday    Sunday
     1          2          3          4          5          6          7
     8          9         10         11         12         13         14
    15         16         17         18         19         20         21
    22         23         24         25         26         27         28
    29         30         31



In [ ]:
import calendar
y=int(input("choose the year "))
m=int(input("choose the month"))
year=y
month=m

print(calendar.month(year,month,day))