# pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
gan=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In [3]:
gn=np.array(gan)

In [4]:
gn

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
df=pd.DataFrame(gn.reshape(4,5),index=["Row1","Row2","Row3","Row4"],columns=["Column1","Column2","Column3","Column4","Column5"])

In [6]:
df.head()

Column1  Column2  Column3  Column4  Column5
Row1        1        2        3        4        5
Row2        6        7        8        9       10
Row3       11       12       13       14       15
Row4       16       17       18       19       20

######## or   df=pd.DataFrame(np.arange(0,20).reshape(4,5),index=["Row1","Row2","Row3","Row4","row5"],columns=["Column1","Column2","Column3","Column4"])

## convert to csv

In [7]:
df.to_csv("test1.csv")

#### (1) .loc (2) .iloc

In [8]:
df.loc["Row1"]

Column1    1
Column2    2
Column3    3
Column4    4
Column5    5
Name: Row1, dtype: int32

In [13]:
df[["Column2"]]

Column2
Row1        2
Row2        7
Row3       12
Row4       17

In [14]:
type(df.loc["Row1"])

pandas.core.series.Series

In [27]:
df.iloc[2:3,3:4]  # represent row and column  # 0,1,2,3 represent row1,row2,row3,row4

Column4
Row3       14

In [15]:
df.iloc[0:4,0:2]

Column1  Column2
Row1        1        2
Row2        6        7
Row3       11       12
Row4       16       17

In [16]:
df.iloc[1:3,0:2]

Column1  Column2
Row2        6        7
Row3       11       12

In [17]:
type(df.iloc[0:5,0:2])

pandas.core.frame.DataFrame

In [18]:
df.iloc[:,:].values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
df.iloc[:,1:].values.shape

(4, 4)

In [20]:
df.iloc[:,1:].values

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [21]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
dtype: int64

In [22]:
df["Column1"].value_counts()

1     1
6     1
11    1
16    1
Name: Column1, dtype: int64

In [23]:
df["Column1"].unique()

array([ 1,  6, 11, 16])

In [24]:
df[["Column2","Column3"]]

Column2  Column3
Row1        2        3
Row2        7        8
Row3       12       13
Row4       17       18

## pandas reading csv

In [31]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv('test1.csv')

In [33]:
df.head()

Unnamed: 0  Column1  Column2  Column3  Column4  Column5
0       Row1        1        2        3        4        5
1       Row2        6        7        8        9       10
2       Row3       11       12       13       14       15
3       Row4       16       17       18       19       20

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  4 non-null      object
 1   Column1     4 non-null      int64 
 2   Column2     4 non-null      int64 
 3   Column3     4 non-null      int64 
 4   Column4     4 non-null      int64 
 5   Column5     4 non-null      int64 
dtypes: int64(5), object(1)
memory usage: 240.0+ bytes


In [35]:
df.describe()

Column1    Column2    Column3    Column4    Column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    8.500000   9.500000  10.500000  11.500000  12.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%     4.750000   5.750000   6.750000   7.750000   8.750000
50%     8.500000   9.500000  10.500000  11.500000  12.500000
75%    12.250000  13.250000  14.250000  15.250000  16.250000
max    16.000000  17.000000  18.000000  19.000000  20.000000

## csv

In [1]:
import pandas as pd
import numpy as np

In [10]:
gan=[1,1.1,1.2,1.3,1.4,1.5,2,2.1,2.2,2.3,2.4,2.5,3,3.1,3.2,3.3,3.4,3.5,4,4.1,4.2,4.3,4.4,4.5,5,5.1,5.2,5.3,5.4,5.5,5.5,6,6,6.1,6.2,6.3,6.4,6.5,7,7.1,7.2,7.3,7.4,7.5,8,8.1,8.2,8.3,8.4,8.5,9,9.1,9.2,9.3,9.4,9.5,123,456,789,258]

In [13]:
ma=np.array(gan)

In [15]:
gan

[1,
 1.1,
 1.2,
 1.3,
 1.4,
 1.5,
 2,
 2.1,
 2.2,
 2.3,
 2.4,
 2.5,
 3,
 3.1,
 3.2,
 3.3,
 3.4,
 3.5,
 4,
 4.1,
 4.2,
 4.3,
 4.4,
 4.5,
 5,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.5,
 6,
 6,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 7,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 8,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 9,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 123,
 456,
 789,
 258]

In [17]:
ma.reshape(6,10)

array([[  1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   2. ,   2.1,   2.2,
          2.3],
       [  2.4,   2.5,   3. ,   3.1,   3.2,   3.3,   3.4,   3.5,   4. ,
          4.1],
       [  4.2,   4.3,   4.4,   4.5,   5. ,   5.1,   5.2,   5.3,   5.4,
          5.5],
       [  5.5,   6. ,   6. ,   6.1,   6.2,   6.3,   6.4,   6.5,   7. ,
          7.1],
       [  7.2,   7.3,   7.4,   7.5,   8. ,   8.1,   8.2,   8.3,   8.4,
          8.5],
       [  9. ,   9.1,   9.2,   9.3,   9.4,   9.5, 123. , 456. , 789. ,
        258. ]])

In [23]:
th=pd.DataFrame(ma.reshape(6,10),index=["Row1","Row2","Row3","Row4","Row5","Row6"],columns=["column1","column2","column3","column4","column5","column6","column7","column8","column9","column10"])

In [24]:
th

column1  column2  column3  column4  column5  column6  column7  column8  \
Row1      1.0      1.1      1.2      1.3      1.4      1.5      2.0      2.1   
Row2      2.4      2.5      3.0      3.1      3.2      3.3      3.4      3.5   
Row3      4.2      4.3      4.4      4.5      5.0      5.1      5.2      5.3   
Row4      5.5      6.0      6.0      6.1      6.2      6.3      6.4      6.5   
Row5      7.2      7.3      7.4      7.5      8.0      8.1      8.2      8.3   
Row6      9.0      9.1      9.2      9.3      9.4      9.5    123.0    456.0   

      column9  column10  
Row1      2.2       2.3  
Row2      4.0       4.1  
Row3      5.4       5.5  
Row4      7.0       7.1  
Row5      8.4       8.5  
Row6    789.0     258.0

### the "th" file to stored in csv "test2" file

In [38]:
th.to_csv("test2.csv")

### retrived from csv file

In [39]:
th=pd.read_csv("test2.csv")

In [40]:
th

Unnamed: 0.1 Unnamed: 0  column1  column2  column3  column4  column5  \
0             0       Row1      1.0      1.1      1.2      1.3      1.4   
1             1       Row2      2.4      2.5      3.0      3.1      3.2   
2             2       Row3      4.2      4.3      4.4      4.5      5.0   
3             3       Row4      5.5      6.0      6.0      6.1      6.2   
4             4       Row5      7.2      7.3      7.4      7.5      8.0   
5             5       Row6      9.0      9.1      9.2      9.3      9.4   

   column6  column7  column8  column9  column10  
0      1.5      2.0      2.1      2.2       2.3  
1      3.3      3.4      3.5      4.0       4.1  
2      5.1      5.2      5.3      5.4       5.5  
3      6.3      6.4      6.5      7.0       7.1  
4      8.1      8.2      8.3      8.4       8.5  
5      9.5    123.0    456.0    789.0     258.0

In [41]:
th.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0.1  6 non-null      int64  
 1   Unnamed: 0    6 non-null      object 
 2   column1       6 non-null      float64
 3   column2       6 non-null      float64
 4   column3       6 non-null      float64
 5   column4       6 non-null      float64
 6   column5       6 non-null      float64
 7   column6       6 non-null      float64
 8   column7       6 non-null      float64
 9   column8       6 non-null      float64
 10  column9       6 non-null      float64
 11  column10      6 non-null      float64
dtypes: float64(10), int64(1), object(1)
memory usage: 616.0+ bytes


In [42]:
th.describe()

Unnamed: 0.1   column1   column2   column3   column4   column5  \
count      6.000000  6.000000  6.000000  6.000000  6.000000  6.000000   
mean       2.500000  4.883333  5.050000  5.200000  5.300000  5.533333   
std        1.870829  2.980213  3.001166  2.931211  2.931211  2.976351   
min        0.000000  1.000000  1.100000  1.200000  1.300000  1.400000   
25%        1.250000  2.850000  2.950000  3.350000  3.450000  3.650000   
50%        2.500000  4.850000  5.150000  5.200000  5.300000  5.600000   
75%        3.750000  6.775000  6.975000  7.050000  7.150000  7.550000   
max        5.000000  9.000000  9.100000  9.200000  9.300000  9.400000   

        column6     column7     column8     column9    column10  
count  6.000000    6.000000    6.000000    6.000000    6.000000  
mean   5.633333   24.700000   80.283333  136.000000   47.583333  
std    2.976351   48.206348  184.075750  319.910788  103.105740  
min    1.500000    2.000000    2.100000    2.200000    2.300000  
25%    3.750000    3.850000    3.950000    4.350000    4.450000  
50%    5.700000    5.800000    5.900000    6.200000    6.300000  
75%    7.650000    7.750000    7.850000    8.050000    8.150000  
max    9.500000  123.000000  456.000000  789.000000  258.000000

In [48]:
th['column2'].value_counts()

1.1    1
2.5    1
4.3    1
6.0    1
7.3    1
9.1    1
Name: column2, dtype: int64

In [61]:
th[th['column8']>100]

Unnamed: 0.1 Unnamed: 0  column1  column2  column3  column4  column5  \
5             5       Row6      9.0      9.1      9.2      9.3      9.4   

   column6  column7  column8  column9  column10  
5      9.5    123.0    456.0    789.0     258.0

In [1]:
import pandas as pd
import numpy as np

In [2]:
from io import StringIO,BytesIO

In [3]:
data=('column1,column2,col3,col4\n'
     'w,x,y,z\n'
     'a,b,1,2\n'
     'c,d,4.5,5.4')

In [4]:
type(data)

str

In [5]:
data

'column1,column2,col3,col4\nw,x,y,z\na,b,1,2\nc,d,4.5,5.4'

In [6]:
StringIO()

In [7]:
ga=pd.read_csv(StringIO(data))

In [8]:
ga

column1 column2 col3 col4
0       w       x    y    z
1       a       b    1    2
2       c       d  4.5  5.4

In [9]:
ga.to_csv('test3.csv')

In [10]:
BytesIO()

In [11]:
ga=pd.read_csv("test3.csv")

In [12]:
ga

Unnamed: 0 column1 column2 col3 col4
0           0       w       x    y    z
1           1       a       b    1    2
2           2       c       d  4.5  5.4

In [14]:
from io import BytesIO,StringIO

In [15]:
gan=('a,b,c\n'
    '1,2,3\n'
    '4,5.5,6\n'
    '7,8.5,9\n')

In [16]:
print(gan)

a,b,c
1,2,3
4,5.5,6
7,8.5,9



In [17]:
type(gan)

str

In [18]:
ga=pd.read_csv(StringIO(gan),dtype=float)

In [19]:
#### to put "dtype to any think object, in, float,string"

In [20]:
ga

a    b    c
0  1.0  2.0  3.0
1  4.0  5.5  6.0
2  7.0  8.5  9.0

In [21]:
ga.to_csv("test4.csv")

In [69]:
ga

a    b    c
0  1.0  2.0  3.0
1  4.0  5.5  6.0
2  7.0  8.5  9.0

In [99]:
ga=pd.read_csv("test4.csv")

In [71]:
ga

Unnamed: 0    a    b    c
0           0  1.0  2.0  3.0
1           1  4.0  5.5  6.0
2           2  7.0  8.5  9.0

In [72]:
ga["b"]

0    2.0
1    5.5
2    8.5
Name: b, dtype: float64

In [ ]:
## example

In [100]:
ma=('a,b,c\n'
   '1,2,3\n'
   '4,5,6\n'
   '7,8,9')

In [101]:
pd.read_csv(StringIO(ma),dtype={'a':int,'b':float,'c':'Int32'})

a    b  c
0  1  2.0  3
1  4  5.0  6
2  7  8.0  9

## take a column in csv file

In [107]:
pd.read_csv(StringIO(ma),index_col=1)

a  c
b      
2  1  3
5  4  6
8  7  9