In [1]:
print(0.1+0.2==0.3)

False


In [2]:
print(1.0+2.0==3.0)

True


In [3]:
type(())

tuple

In [4]:
type([])

list

In [5]:
type({})

dict

In [33]:
import numpy as np

In [34]:
a=[1,2,3,4,5,6,7,8,9]
arr=np.array(a)

In [35]:
val=2

arr>=2

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [36]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[arr<=2]

array([1, 2])

In [89]:
import numpy as np

In [90]:
arr1=np.arange(0,10).reshape(2,5)

In [91]:
arr2=np.arange(0,10).reshape(2,5)

In [92]:

arr1 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [95]:
np.ones(4,dtype=float)

array([1., 1., 1., 1.])

In [96]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [1]:
x=1#2#3

In [2]:
print(x)

1


In [1]:
i=11
for i in range(i-1):
    print(i)
    

0
1
2
3
4
5
6
7
8
9


In [3]:
a=int(input("enter the num"))
for i in range(1,a+1):
    for j in range(1,i+1):
        print(i,end="")
    print()    

enter the num10
1
22
333
4444
55555
666666
7777777
88888888
999999999
10101010101010101010


In [12]:
b=int(input("enter the num"))
for i in range(1,b):
    for j in range(1,i+1):
        print(i,end="")
    print()    

enter the num10
1
22
333
4444
55555
666666
7777777
88888888
999999999


In [5]:
a=int(input("enter the num"))
for i in range(1,a+1):
    for j in range(a,-1):
        print("*",end="")
    print()    

enter the num10












In [1]:
import turtle
ga=turtle.Turtle()
for i in range(4):
    ga.forward(100)
    ga.right(90)
    

In [34]:
a=10
for i in range(a):
    for j in range(i):
        print("*",end="")
    print()


*
**
***
****
*****
******
*******
********
*********


In [6]:
a="mathi vanan"
for i in a:
    print(i)

m
a
t
h
i
 
v
a
n
a
n


In [15]:
a=10
for i in range(1,a+1):
    for j in range(1,i+1):
        print(j,end="")
    print()

1
12
123
1234
12345
123456
1234567
12345678
123456789
12345678910


In [27]:
for i in range(20,10,-1):
    print(i)

20
19
18
17
16
15
14
13
12
11


In [39]:
av=10
a=int(input("enter you want="))
for i in range(1,a+1):
    if i>av:
        print("out of stock")
        break
    print(i,"phone")
print()    

enter you want=20
1 phone
2 phone
3 phone
4 phone
5 phone
6 phone
7 phone
8 phone
9 phone
10 phone
out of stock



## while

In [11]:
av=10
a=int(input("enter you want"))
i=1
while i<=a:
    
    if i>av:
        print(i,"out of stock")
        break
        
    print(i,"phone")
    i+=1
    
print()

enter you want20
1 phone
2 phone
3 phone
4 phone
5 phone
6 phone
7 phone
8 phone
9 phone
10 phone
11 out of stock



In [12]:
print("mathi")

mathi


In [20]:
a=int(input("enter you want"))
for i in range(1,a+1):
    for j in range(1,i+1):
        print(j,end="")
    print()

enter you want10
1
12
123
1234
12345
123456
1234567
12345678
123456789
12345678910


In [22]:
print("#",end="")
print()
print("#",end="")

#
#

In [30]:
a=int(input("enter you want"))
for i in range(a):
    print("*")
    for j in range(a):
        print(i,end="")
    print()

enter you want5
*
00000
*
11111
*
22222
*
33333
*
44444


In [ ]:
b=int(input("enter the num"))
for i in range(b):
    for j in range(b-i):
        print("*",end=" ")
    print()

In [39]:
for i in range(5):
    for j in range(i):
        print(i,end="")
    print("")


1
22
333
4444


In [9]:
print(3**8) # to knoew the power value

6561


In [12]:
print(8//3) # to know the % value
  
print(8%3)

2
2


In [1]:
num=[1,5,45,78,12,14,15,13,16,18,5,4,6,8,7,9,2,3,10]
num.sort()
print(num)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 18, 45, 78]


In [3]:
num.sort(reverse=True)
print(num)

[78, 45, 18, 16, 15, 14, 13, 12, 10, 9, 8, 7, 6, 5, 5, 4, 3, 2, 1]


In [8]:
fr=["apple","nanana","mango","cherry","berry"]
print(fr)
fr.append("candy")
print(fr)

['apple', 'nanana', 'mango', 'cherry', 'berry']
['apple', 'nanana', 'mango', 'cherry', 'berry', 'candy']


In [13]:
ma=[1,2,3,4,5,6,7,8,9,10,11,12]
print(ma)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [14]:
print(fr+ma)

['apple', 'nanana', 'mango', 'cherry', 'berry', 'candy', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


## lambda

In [1]:
mat=lambda num: num+50
print(mat(20))
print(mat(10))

70
60


In [6]:
b="mca "
m=input("enter your name")
print(b+m)


enter your namemathi
mca mathi


In [7]:
m= input("enter name")
print("hi "+m+" mca")

enter namemathi
hi mathi mca


In [2]:
a=int(input("enter 1st num"))
b=int(input("enter end num"))
c=int(input("1.addition\n2.subtraction\n3.multiplication\n4.division\n"))
if c==1:
    print("addition table")
    d=int(input("enter table you want"))
    for i in range(a,b+1):
        t=i+d
        print(i,"+",d,"=",t)   
    
elif c==2:
    print("subtraction table")
    d=int(input("enter table you want"))
    for i in range(a,b,-1):
        t=i-d
        print(i,"-",d,"=",t)
           
elif c==3:
        print("multiplication table")
        d=int(input("enter table you want"))
        for i in range(a,b+1):
            t=i*d
            print(i,"*",d,"=",t) 
            
elif c==4:
        print("division table")
        d=int(input("enter table you want"))
        for i in range(a,b):
            t=i/d
            print(i,"/",d,"=",t)
            
            

enter 1st num1
enter end num10
1.addition
2.subtraction
3.multiplication
4.division
3
multiplication table
enter table you want5
1 * 5 = 5
2 * 5 = 10
3 * 5 = 15
4 * 5 = 20
5 * 5 = 25
6 * 5 = 30
7 * 5 = 35
8 * 5 = 40
9 * 5 = 45
10 * 5 = 50


In [6]:
n=int(input("enter your num"))
k=n-1
for i in range(0,n):
    for j in range(0,k):
        print(end=" ")
    k=k-1
    for j in range(0,i+1):
        print("*",end="")
        
    print("")

enter your num5
    *
   **
  ***
 ****
*****


In [5]:
a=int(input("enter your choice"))
n=65

for i in range(0,a):
    for j in range(0,i+1):
        ch=chr(n)
        print(ch,end="")
    n=n+1
    print()

enter your choice5
A
BB
CCC
DDDD
EEEEE


In [25]:
a=int(input("enter your choice"))
n=65

for i in range(0,a):
    for j in range(0,i+1):
        ch=chr(n)
        print(ch,end="")
        n=n+1
    print()

enter your choice5
A
BC
DEF
GHIJ
KLMNO


In [2]:
def fun():
    return 10,11,12
print(fun())

(10, 11, 12)


In [3]:
y=10
def add():
    r=15
    r=r+25
    print(r)
add()
print(y)

40
10


In [5]:
fruit="10"
fruit=fruit+"5"
egg=int(fruit)+3
print(float(egg))

108.0


In [6]:
fruit=10
fruit=fruit+5
egg=int(fruit)+3
print(float(egg))

18.0


In [8]:
x=2,
y=2
print(type(x)==type(y))

True


In [9]:
x=2
y=2
print(type(x)==type(y))

True


In [10]:
a=3
a=33
print(a==a)

True


In [7]:
def pat(n):
    k=n-1
    for i in range(0,n):
        
        for j in range(0,k):
            print(end=" ")
        k=k-1
        for j in range(0,i+1):
            print("*",end="")
            
        print("")

n=int(input("enter the input"))
pat(n)



enter the input5
    *
   **
  ***
 ****
*****


In [10]:
x=50
y=100
print(x and y)

100


In [33]:
from array import *
mylist=["gan","esh"]
for i in (mylist):
    mylist.append(i.upper())
print(mylist)

MemoryError: 

In [34]:
a=["1","2","3","4","5","6","7","8","9"]
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9


In [40]:
l=list("12345")
#l[0]=l[1]=5
print(l)

['1', '2', '3', '4', '5']


In [41]:
l=list("12345")
l[0]=l[1]=5
print(l)

[5, 5, '3', '4', '5']


In [48]:
st1="do"
st2="more"
lst=["write","less","code"]

st3=" ".join(lst)+","+st1+" "+st2

print(st3)

write less code,do more


In [39]:
a=35
print("%f"%a)

35.000000


In [49]:
a=2*2//2
b=3//2*3
print(a,b)

2 3


In [21]:
if(y<=18):
    y=y+3
    print(y)

NameError: name 'y' is not defined

In [1]:
import pandas as pd
import numpy as np

In [4]:
a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
b=np.array(a)

In [5]:
b.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
df=pd.DataFrame(b.reshape(5,4),index=["a","b","c","d","e"],columns=["f","g","h","i"])

In [19]:
df

f   g   h   i
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20

In [52]:
df[0:5]

f   g   h   i
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20

In [53]:
df.head()

f   g   h   i
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20

In [58]:
df.tail(4)

f   g   h   i
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20

In [59]:
df.T

a  b   c   d   e
f  1  5   9  13  17
g  2  6  10  14  18
h  3  7  11  15  19
i  4  8  12  16  20

In [64]:
for i in range(-2,-5,-1):
    print(i,end=",")

-2,-3,-4,

prime numbers

In [ ]:
n=int(input("enter the value"))
count=0
for i in n(1,n+1):
    if n%i==0:
        count +=1
if count ==2:
    print(n,"is a prime number")
else:
    print(n,"not a prime num")